### ISSUE TITLE
Upcoming changes to `srvyr` break test

### ISSUE THREAD

**Issue by gergness** [iNZightVIT/iNZightTools#177]
Hi there, this is a very cool project!

`srvyr` is updating to use the new version of `survey::svyquantile` by default, and in doing so breaks a test in `iNZightTools`.

The new version is available at `remotes::install_github("gergness/srvyr")` and will likely be version 1.1.0 upon release.

Now that the survey package version 4.1 has an update on CRAN, can you change this line:

https://github.com/iNZightVIT/iNZightTools/blob/77c17c9988cb30ae350443e55068ebee88ab12a0/tests/testthat/test_aggregateData.R#L88

to something like:
```r
if (utils::packageVersion("srvyr") <= "1.0.1") {
```

(There's also a function `srvyr::survey_old_quantile` you could use if you prefer.)

Thank you!

**Comment by tmelliott** [comment]
Cheers - I'll try get that updated ASAP.

**Comment by gergness** [comment]
Hey, hope you're doing well, despite everything. I can imagine any number of reasons why it'd take a little longer, but was wondering if you knew when you'd be able to do a CRAN release with this change?

**Comment by tmelliott** [comment]
Kia ora - I'll do that this weekend! I think it's been long enough since my last update to not upset CRAN ..
