### ISSUE TITLE
`smart_read` urls

### ISSUE THREAD

**Issue by chrk623** [iNZightVIT/iNZightTools#207]
Is it expected behaviour to fail when reading from google sheets?

```R
smart_read("https://docs.google.com/spreadsheets/d/e/2PACX-1vT7tFLpsJzy9o4kqmF7AuITTgkOdzFd5OH14-O3nWjU08LZTomNr_rWLKboA-GIGfsfnTRH2LL0vYCx/pub?gid=0&single=true&output=csv")
```

**Comment by tmelliott** [comment]
That, I believe, is due to there not being enough information to detect the delimiter - which is handled by the 'vroom' package, by default, and usually only an issue for small test files.
