### ISSUE TITLE
Switch `full.file = TRUE|FALSE` to `preview = FALSE|TRUE`

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightTools#4]
Again the main use of the function is to import data into R (the full file is to be expected by default).

Since preview is a secondary action, there's no need to add the attribute `full.file = TRUE` to every returned data frame; it's only necessary to identify previews (i.e., via the attribute `preview = TRUE`). 
NOTE: this does __not__ have to be added to every object, __only on previews__. If the data frame is not a preview, then it simply does not have any attributes to say that it is.

Then the `isFullFile()` function needs to be converted to `isPreview`, which simply checks for the existence of an attribute called `preview`.

***
The ideal workflow would be as such:
```{R}
d <- iNZread("filename.ext", ..., preview = TRUE)

# do stuff with d; determine extra arguments (...) for iNZread

# ready to import into iNZight?
if (isPreview(d))
  d <- iNZread("filename.ext", ...)  ## no preview argument (default is FALSE)

# now d is the full data set; can load into main iNZight program
```

**Comment by agup792** [comment]
That will work. But, in functions like iNZread.dta, which always return the full file, if the preview is true and I set it as such, how will you know from the returned data frame that it is the complete file even though preview = TRUE. 

If we do it this way, we will be reading the file twice always (even if full file was already there and no changes were made).

**Comment by tmelliott** [comment]
```{R}
data <- iNZread('path/to/file', preview = TRUE, ...)
{{ do stuff }}
if (isPreview(data)) data <- iNZread('path/to/file', {preview = FALSE}, ...)
```

i.e., the user checks that the file __is__ only a preview before reading it again; if it's not a preview, then just use what was read.
